def hangdraw(step):
    if step ==1:
        print("")
        print(" ")
        print(" ")
        print(" ")
        print(" ")
        print(" ||")
        print("/||\\")
        print("==========")
    elif step == 2:
        print("")
        print(" ||")
        print(" ||")
        print(" ||")
        print(" ||")
        print(" ||")
        print("/||\\")
        print("==========")
    elif step == 3:
        print("")
        print(" ||======")
        print(" ||/ ")
        print(" || ")
        print(" || ")
        print(" || ")
        print("/||\\")
        print("==========")
    elif step == 4:
        print("")
        print(" ||======")
        print(" ||/    |")
        print(" ||     o")
        print(" ||")
        print(" ||")
        print("/||\\")
        print("==========")
    else:
        print("")
        print(" ||======")
        print(" ||/    |")
        print(" ||     o")
        print(" ||    /|\\")
        print(" ||    / \\")
        print("/||\\")
        print("==========")

